name: Pin requirements

on:
  workflow_call:

jobs:
  pin_requirements:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - name: Debug access to PAT
      run: |
        echo "Accessing the PAT secret"
        echo "GITHUB_TOKEN is available: ${{ secrets.PAT_TOKEN }}"

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Write requirements.txt
      run: |
        poetry export --without-hashes --output requirements.txt

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add requirements.txt
        git commit -m "Update requirements.txt generated by Poetry"
        git push