name: Test Testing

on:
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install Dependencies
      env:
        PIP_CONSTRAINT: .github/workflows/constraints.txt
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install poetry
        poetry install

    - name: Export requirements.txt
      uses: actions/upload-artifact@v4
      with:
        name: poetry export --output requirements.txt
        path: requirements.txt
